# Topic: Indexing, Slicing, and Iteration in NumPy

Author: Hamna Munir
Repository: Python-Libraries-for-AI-ML
Goal: Learn how to access and manipulate NumPy array elements using indexing, slicing, and iteration.

---
## Learning Outcomes
- How indexing works in NumPy
- How slicing is used to extract parts of an array
- How to iterate over NumPy arrays
- Differences between basic indexing and advanced slicing

---

## 1. Importing NumPy

In [ ]:
import numpy as np

## 2. Basic Indexing

In [ ]:
arr = np.array([10, 20, 30, 40, 50])
print("Array:", arr)
print("First element:", arr[0])
print("Third element:", arr[2])
print("Last element:", arr[-1])

Array: [10 20 30 40 50]
First element: 10
Third element: 30
Last element: 50

## 3. 2D Array Indexing

In [ ]:
arr2D = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("2D Array:\n", arr2D)
print("Element at row 0, column 1:", arr2D[0, 1])
print("Element at row 2, column 2:", arr2D[2, 2])

2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Element at row 0, column 1: 2
Element at row 2, column 2: 9

## 4. Slicing in NumPy

In [ ]:
arr = np.array([10, 20, 30, 40, 50, 60, 70])
print("Original Array:", arr)
print("Slice 1 (index 1 to 4):", arr[1:4])
print("Slice 2 (start to index 3):", arr[:3])
print("Slice 3 (index 3 to end):", arr[3:])
print("Slice 4 (step=2):", arr[0:7:2])

Original Array: [10 20 30 40 50 60 70]
Slice 1 (index 1 to 4): [20 30 40]
Slice 2 (start to index 3): [10 20 30]
Slice 3 (index 3 to end): [40 50 60 70]
Slice 4 (step=2): [10 30 50 70]

## 5. Slicing in 2D Arrays

In [ ]:
arr2D = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print("2D Array:\n", arr2D)
print("\nExtract first two rows:\n", arr2D[0:2, :])
print("\nExtract first two columns:\n", arr2D[:, 0:2])
print("\nExtract middle elements (rows 1:3, cols 1:3):\n", arr2D[1:3, 1:3])

2D Array:
[[10 20 30]
 [40 50 60]
 [70 80 90]]

Extract first two rows:
[[10 20 30]
 [40 50 60]]

Extract first two columns:
[[10 20]
 [40 50]
 [70 80]]

Extract middle elements (rows 1:3, cols 1:3):
[[50 60]
 [80 90]]

## 6. Iteration in NumPy

In [ ]:
arr = np.array([5, 10, 15])
print("1D Array Iteration:")
for x in arr:
    print(x)

1D Array Iteration:
5
10
15

In [ ]:
print("2D Array Iteration (row-wise):")
for row in arr2D:
    print(row)

2D Array Iteration (row-wise):
[10 20 30]
[40 50 60]
[70 80 90]

In [ ]:
print("Iterating over each element:")
for row in arr2D:
    for item in row:
        print(item, end=" ")

Iterating over each element:
10 20 30 40 50 60 70 80 90

## Summary
- Indexing is used to access a specific element.
- Slicing extracts parts of an array using `start:end:step`.
- 2D arrays use row and column indexing.
- Iteration lets you loop through arrays.
- Slicing works the same way for 1D and 2D arrays.

Mastering indexing and slicing is important for AI/ML workflows.