# Topic: Indexing, Slicing, and Iteration in NumPy

**Author:** Hamna Munir  
**Repository:** Python-Libraries-for-AI-ML  
**Goal:** Learn how to access and manipulate NumPy array elements using indexing, slicing, and iteration.

---

## Learning Outcomes
After completing this notebook, you will be able to:

- Explain 1D, 2D and higher-dimension indexing and how to reference elements.
- Use slicing to extract subarrays with start:end:step syntax and axis-aware slicing.
- Iterate over arrays efficiently and understand row-wise vs element-wise traversal.
- Distinguish views (shallow) from copies (deep) and avoid common pitfalls.

---


## 1. Importing NumPy

Import NumPy as the conventional alias `np` and verify the version.

In [1]:
import numpy as np

print('NumPy version:', np.__version__)

NumPy version: 1.24.0


## 2. Basic Indexing (Detailed Explanation)

► **Definition:** Indexing selects a single element from an array using integer positions. NumPy uses **0-based indexing**.

► **1D arrays:** use a single index `arr[i]`.

► **2D arrays:** use `arr[row, column]` (preferred) or `arr[row][column]`.

► **Negative indices:** `-1` refers to the last element, `-2` to the second last, and so on.

**Note:** Indexing returns a scalar (for single element) or an array (for multi-index selection).


In [2]:
arr = np.array([10, 20, 30, 40, 50])
print('Array:', arr)
print('First element:', arr[0])
print('Third element:', arr[2])
print('Last element:', arr[-1])

Array: [10 20 30 40 50]
First element: 10
Third element: 30
Last element: 50


## 3. 2D Array Indexing (Detailed Explanation)

► **Accessing elements:** Use `arr[row, col]`. Rows and columns are 0-indexed.

► **Example use case:** Selecting a feature value for a given sample in a dataset represented as a 2D array (`samples × features`).


In [3]:
arr2D = np.array([[1,2,3], [4,5,6], [7,8,9]])
print('2D Array:\n', arr2D)
print('Element at row 0, column 1:', arr2D[0, 1])
print('Element at row 2, column 2:', arr2D[2, 2])

2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Element at row 0, column 1: 2
Element at row 2, column 2: 9


## 4. Slicing (Detailed Explanation)

► **Definition:** Slicing extracts a subarray using `start:end:step` semantics. The `end` index is exclusive.

► **1D slicing:** `arr[start:end]` returns elements from `start` to `end-1`.

► **2D slicing:** use `arr[row_start:row_end, col_start:col_end]` to slice along each axis.

► **Step parameter:** `arr[::step]` selects every `step`-th element.

**Important:** Slicing returns a **view** (not a copy) — modifying the slice modifies the original array unless `.copy()` is used.


In [4]:
arr = np.array([10, 20, 30, 40, 50, 60, 70])
print('Original Array:', arr)
print('Slice 1 (index 1 to 4):', arr[1:4])
print('Slice 2 (start to index 3):', arr[:3])
print('Slice 3 (index 3 to end):', arr[3:])
print('Slice 4 (step=2):', arr[0:7:2])

Original Array: [10 20 30 40 50 60 70]
Slice 1 (index 1 to 4): [20 30 40]
Slice 2 (start to index 3): [10 20 30]
Slice 3 (index 3 to end): [40 50 60 70]
Slice 4 (step=2): [10 30 50 70]


## 5. 2D Slicing (Detailed Explanation)

► Use `arr[row_start:row_end, col_start:col_end]` to slice across rows and columns.

► This is useful to extract submatrices, batches of samples, or feature subsets.


In [5]:
arr2D = np.array([[10,20,30],[40,50,60],[70,80,90]])
print('2D Array:\n', arr2D)
print('\nExtract first two rows:\n', arr2D[0:2, :])
print('\nExtract first two columns:\n', arr2D[:, 0:2])
print('\nExtract middle elements (rows 1:3, cols 1:3):\n', arr2D[1:3, 1:3])

2D Array:
[[10 20 30]
 [40 50 60]
 [70 80 90]]

Extract first two rows:
[[10 20 30]
 [40 50 60]]

Extract first two columns:
[[10 20]
 [40 50]
 [70 80]]

Extract middle elements (rows 1:3, cols 1:3):
[[50 60]
 [80 90]]


## 6. Iteration (Detailed Explanation)

► Iteration lets you traverse array elements. Iteration over a 2D array yields rows; use nested loops or `.flat` to traverse elements.

► Prefer vectorized operations for performance; iteration is useful for custom element-wise logic when necessary.


In [6]:
arr = np.array([5, 10, 15])
print('1D Array Iteration:')
for x in arr:
    print(x)

1D Array Iteration:
5
10
15


In [7]:
print('2D Array Iteration (row-wise):')
for row in arr2D:
    print(row)

2D Array Iteration (row-wise):
[10 20 30]
[40 50 60]
[70 80 90]


In [8]:
print('Iterating over each element:')
for row in arr2D:
    for item in row:
        print(item, end=' ')

Iterating over each element:
10 20 30 40 50 60 70 80 90


## 7. Views vs Copies (Detailed Explanation)

► **View (shallow):** Slicing returns a view referencing the same memory. Modifying the view will change the original array.

► **Copy (deep):** Use `.copy()` to create an independent copy when you need to modify data without affecting the original.

Example demonstrates this behavior.

In [9]:
arr = np.array([1,2,3,4])
view_arr = arr[1:3]
copy_arr = arr[1:3].copy()

print('Original:', arr)
view_arr[0] = 9
print('View Modified:', view_arr)
print('Original after modifying view:', arr)

copy_arr[0] = 9
print('Copy Modified:', copy_arr)
print('Original remains:', arr)

Original: [1 2 3 4]
View Modified: [9 3]
Original after modifying view: [1 9 3 4]
Copy Modified: [9 3]
Original remains: [1 9 3 4]


## 8. Practice Tasks

- Extract the last 3 elements from a 1D array.
- From a 3×3 matrix, extract the second column.
- Iterate over a 2D array and print only even numbers.
- Slice elements from index 2 to 8 from an array of size 10.

Try to complete these tasks and compare your outputs to the examples above.

## Summary

- Indexing provides direct access to elements using integer positions.
- Slicing extracts subarrays and returns views by default.
- 2D indexing uses `arr[row, col]` to access elements in matrices.
- Iteration can be row-wise, element-wise, or via `.flat`.
- Use `.copy()` when you need an independent array copy to avoid side-effects.

Mastering these techniques is essential for data preprocessing and handling arrays in AI/ML pipelines.