# Topic: Indexing, Slicing, and Iteration in NumPy
---
**Author:** Hamna Munir  
**Repository:** Python-Libraries-for-AI-ML  
**Goal:** Understand how to access, slice, and iterate NumPy arrays effectively.
---
### Learning Outcomes
In this notebook, you will learn:
- How to index 1D, 2D, and 3D NumPy arrays
- How to perform slicing operations
- How iteration works in NumPy
- The difference between shallow and deep copies
- Practical use-cases in AI/ML
---

## Indexing in NumPy
Indexing allows you to access individual elements of an array.

### 1D Array Indexing

In [1]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
print("Array:", arr)
print("First element:", arr[0])
print("Last element:", arr[-1])

Array: [10 20 30 40 50]
First element: 10
Last element: 50


### 2D Array Indexing
Use format `array[row][col]` or `array[row, col]`.

In [2]:
arr2D = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

print("2D Array:\n", arr2D)
print("Element (0,1):", arr2D[0, 1])
print("Element (2,2):", arr2D[2, 2])

2D Array:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]]
Element (0,1): 2
Element (2,2): 9


## Slicing in NumPy
Slicing format: `array[start:end:step]`

In [3]:
arr = np.array([10, 20, 30, 40, 50, 60])
print("Original:", arr)
print("Slice 1 (1:4):", arr[1:4])
print("Slice 2 (:3):", arr[:3])
print("Slice 3 (every second):", arr[::2])

Original: [10 20 30 40 50 60]
Slice 1 (1:4): [20 30 40]
Slice 2 (:3): [10 20 30]
Slice 3 (every second): [10 30 50]


### Slicing 2D Arrays

In [4]:
arr2D = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

print("Array:\n", arr2D)
print("First two rows:\n", arr2D[:2, :])
print("Column 1 to 3:\n", arr2D[:, 1:3])

Array:\n [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
First two rows:\n [[1 2 3 4]
 [5 6 7 8]]
Column 1 to 3:\n [[ 2  3]
 [ 6  7]
 [10 11]]


## Iteration in NumPy
NumPy allows iteration row-wise and element-wise.

In [5]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

for row in arr:
    print("Row:", row)

Row: [1 2 3]
Row: [4 5 6]


### Iterating Over Each Element

In [6]:
for element in arr.flat:
    print(element, end=" ")

1 2 3 4 5 6 

## Copy vs View
NumPy slicing creates a **view** (not a copy). Both share memory.

To create a separate copy, use `.copy()`.

In [7]:
arr = np.array([1, 2, 3, 4])
view_arr = arr[1:3]
copy_arr = arr[1:3].copy()

print("Original:", arr)
view_arr[0] = 9
print("View Modified:", view_arr)
print("Original after modifying view:", arr)

copy_arr[0] = 9
print("Copy Modified:", copy_arr)
print("Original remains:", arr)

Original: [1 2 3 4]
View Modified: [1 9 3 4]
Original after modifying view: [1 9 3 4]
Copy Modified: [1 9 3 4]
Original remains: [1 9 3 4]


## Practice Tasks
- Extract the last 3 elements from a 1D array.
- Slice a 2D array to get a 2x2 submatrix.
- Iterate through a 3D array.
- Modify a slice and observe if the original array changes.
- Create a deep copy and modify it.


## Summary
- Indexing provides direct access to elements.
- Slicing extracts parts of an array.
- Iteration can be row-wise or element-wise.
- Views share memory; copies do not.
- Indexing and slicing are essential in AI/ML for data preprocessing.
---