# Topic: NumPy Operations

**Author:** Hamna Munir  
**Repository:** Python-Libraries-for-AI-ML  
**Goal:** Learn fundamental NumPy mathematical, statistical, and array-wise operations.

---

## Learning Outcomes
After completing this notebook, you will be able to:

- Perform arithmetic operations on NumPy arrays.
- Use universal functions (ufuncs) for fast element-wise processing.
- Apply aggregation/statistical functions such as sum, mean, min, max, and std.
- Use vectorized operations efficiently without loops.
- Perform matrix operations like dot product and matrix multiplication.

---


## 1. Importing NumPy

Import NumPy as the conventional alias `np` and verify the version.

In [1]:
import numpy as np

print('NumPy version:', np.__version__)

NumPy version: 1.24.0


## 2. Basic Arithmetic Operations

NumPy performs element-wise operations automatically on arrays of the same shape.

► **Supported operations:** `+`, `-`, `*`, `/`, `//`, `**`, `%`

These operations are vectorized (performed without explicit loops).

In [2]:
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])

print('Array A:', A)
print('Array B:', B)
print('Addition:', A + B)
print('Subtraction:', A - B)
print('Multiplication:', A * B)
print('Division:', A / B)

Array A: [1 2 3]
Array B: [4 5 6]
Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]
Division: [0.25 0.4  0.5 ]


## 3. Universal Functions (UFuncs)

NumPy provides fast mathematical functions that operate element-wise.

► Common ufuncs:
- `np.sqrt()`
- `np.exp()`
- `np.log()`
- `np.sin()`, `np.cos()`, `np.tan()`

These functions are optimized in C for high performance.

In [3]:
arr = np.array([1, 4, 9, 16])
print('Array:', arr)
print('Square root:', np.sqrt(arr))
print('Exponential:', np.exp(arr))
print('Natural log:', np.log(arr))

Array: [1 4 9 16]
Square root: [1. 2. 3. 4.]
Exponential: [2.71828183 54.59815003 8103.08392758 8886110.52050787]
Natural log: [0.         1.38629436 2.19722458 2.77258872]


## 4. Statistical / Aggregation Functions

NumPy provides fast built-in operations for summarizing data.

► **Common aggregation functions:**
- `np.sum()`
- `np.mean()`
- `np.min()`, `np.max()`
- `np.std()` (standard deviation)
- `np.median()`

In [4]:
arr = np.array([10, 20, 30, 40, 50])
print('Array:', arr)
print('Sum:', np.sum(arr))
print('Mean:', np.mean(arr))
print('Min:', np.min(arr))
print('Max:', np.max(arr))
print('Standard Deviation:', np.std(arr))

Array: [10 20 30 40 50]
Sum: 150
Mean: 30.0
Min: 10
Max: 50
Standard Deviation: 14.142135623730951


## 5. Vectorized Operations (No Loops Needed)

Vectorization allows operations to run extremely fast by avoiding Python loops.

► Example: Convert Celsius to Fahrenheit using a single expression.

In [5]:
celsius = np.array([0, 10, 20, 30, 40])
fahrenheit = celsius * 9/5 + 32
print('Celsius:', celsius)
print('Fahrenheit:', fahrenheit)

Celsius: [ 0 10 20 30 40]
Fahrenheit: [ 32.  50.  68.  86. 104.]


## 6. Matrix Operations

NumPy supports matrix-level mathematical operations:
► `np.dot()` – dot product
► `@` – matrix multiplication operator
► `np.transpose()` – transpose matrix

In [6]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print('Matrix A:\n', A)
print('\nMatrix B:\n', B)
print('\nDot Product:\n', np.dot(A, B))

Matrix A:
[[1 2]
 [3 4]]

Matrix B:
[[5 6]
 [7 8]]

Dot Product:
[[19 22]
 [43 50]]


## 7. Practice Tasks

- Add two 1D arrays element-wise.
- Compute square, cube, and square root of a given array.
- Find the mean, median, and standard deviation of an array.
- Convert kilometers to miles using vectorized operations.
- Perform matrix multiplication on two 3×3 matrices.


## Summary

- NumPy operations are fast and vectorized.
- Arithmetic operators work element-wise.
- UFuncs perform optimized mathematical operations.
- Aggregation functions summarize data efficiently.
- Matrix operations enable advanced linear algebra.

Understanding these operations is essential for AI/ML data processing and scientific computing.