# Topic: Reshaping Arrays in NumPy

**Author:** Hamna Munir  
**Repository:** Python-Libraries-for-AI-ML  
**Goal:** Learn how to reshape, flatten, ravel, and modify NumPy array dimensions effectively.

---

## Learning Outcomes
After completing this notebook, you will be able to:

- Understand how shapes and dimensions work in NumPy.
- Use `reshape()` to convert arrays into different dimensions.
- Use `flatten()` and `ravel()` to convert multi-dimensional arrays into 1D.
- Use `resize()` to modify the size of arrays.
- Understand the difference between views and copies during reshaping.

---


## 1. Importing NumPy

Import NumPy as the conventional alias `np` and verify the version.

In [1]:
import numpy as np

print('NumPy version:', np.__version__)

NumPy version: 1.24.0


## 2. Understanding Array Shape

Each NumPy array has a shape that defines the number of elements along each dimension.

► `arr.shape` returns a tuple representing the array's dimensions.

► A 1D array has shape `(n,)`, while a 2D array has shape `(rows, columns)`.

In [2]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([[1, 2, 3], [4, 5, 6]])

print('1D Array shape:', arr1.shape)
print('2D Array shape:', arr2.shape)

1D Array shape: (5,)
2D Array shape: (2, 3)


## 3. Reshaping Arrays

`reshape()` allows changing the dimensions of an array **without changing the data**.

► Total elements before and after reshaping must be the same.

► Use `-1` to let NumPy automatically compute the dimension.

In [3]:
arr = np.array([1, 2, 3, 4, 5, 6])
print('Original Array:', arr)

print('Reshaped to 2x3:')
print(arr.reshape(2, 3))

print('Reshaped using -1:')
print(arr.reshape(-1, 2))

Original Array: [1 2 3 4 5 6]
Reshaped to 2x3:
[[1 2 3]
 [4 5 6]]
Reshaped using -1:
[[1 2]
 [3 4]
 [5 6]]


## 4. Flattening and Raveling

► `flatten()` → returns a **copy** of the array in 1D.

► `ravel()` → returns a **view** of the array when possible.

Both are used to convert multi-dimensional data into a 1D vector.

In [4]:
arr2D = np.array([[1, 2, 3], [4, 5, 6]])
print('2D Array:\n', arr2D)
print('Flattened:', arr2D.flatten())
print('Raveled:', arr2D.ravel())

2D Array:
[[1 2 3]
 [4 5 6]]
Flattened: [1 2 3 4 5 6]
Raveled: [1 2 3 4 5 6]


## 5. Using resize()

`resize()` changes the shape of the array **in place**.

► If new size is larger, NumPy repeats elements.

► If smaller, elements are truncated.

In [5]:
arr = np.array([1, 2, 3, 4])
print('Original:', arr)

arr.resize((2, 2))
print('Resized to 2x2:')
print(arr)

arr.resize((3, 3))
print('Resized to 3x3 (fills repeated values):')
print(arr)

Original: [1 2 3 4]
Resized to 2x2:
[[1 2]
 [3 4]]
Resized to 3x3 (fills repeated values):
[[1 2 3]
 [4 1 2]
 [3 4 1]]


## 6. View vs Copy in Reshaping

► `reshape()` returns a **view** when possible.

► Modifying a view changes the original array.

**Example below demonstrates this.**

In [6]:
arr = np.array([10, 20, 30, 40])
reshaped = arr.reshape(2, 2)  # view
print('Original:', arr)
print('Reshaped View:\n', reshaped)

reshaped[0, 0] = 99
print('Modified Reshaped View:\n', reshaped)
print('Original after modifying view:', arr)

Original: [10 20 30 40]
Reshaped View:
[[10 20]
 [30 40]]
Modified Reshaped View:
[[99 20]
 [30 40]]
Original after modifying view: [99 20 30 40]


## 7. Practice Tasks

- Reshape an array of size 12 into a 3×4 matrix.
- Convert a 3×3 array into a 1D array using both `flatten()` and `ravel()`.
- Resize a 1D array of length 5 into a 2×4 array and observe repeated values.
- Use reshape with `-1` to automatically calculate dimensions.
- Check whether reshaping returned a copy or a view.


## Summary

- Array reshaping changes dimensions without altering data.
- `reshape()` is powerful and often returns a **view**.
- `flatten()` returns a **copy**, while `ravel()` returns a **view**.
- `resize()` modifies the original array in place.
- Understanding shapes and dimensions is essential for data preprocessing in AI/ML.
