# Topic: Fancy Indexing in NumPy

**Author:** Hamna Munir  
**Repository:** Python-Libraries-for-AI-ML  
**Goal:** Learn how to use advanced indexing techniques such as integer indexing, boolean masking, and multi-dimensional fancy indexing.

---
## Learning Outcomes
After completing this notebook, you will be able to:
- Understand integer-array indexing and select elements using lists of positions.
- Apply boolean masking to filter array elements based on conditions.
- Perform fancy indexing in 2D arrays using row and column index lists.
- Modify arrays using fancy indexing.
- Distinguish fancy indexing from slicing.

---


## 1. Importing NumPy
NumPy is imported as the standard alias `np`.

In [1]:
import numpy as np
print("NumPy version:", np.__version__)

NumPy version: 1.24.0


## 2. Integer Array Indexing (Detailed Explanation)

**Definition:** Fancy indexing allows selecting multiple elements using lists or arrays of integers.

► Unlike slicing, which selects continuous ranges, fancy indexing lets you pick **specific positions** in any order.

**Example:** Selecting elements at indices `[0, 2, 4]`.

In [2]:
arr = np.array([10, 20, 30, 40, 50])
indices = [0, 2, 4]
print("Array:", arr)
print("Selected elements:", arr[indices])

Array: [10 20 30 40 50]
Selected elements: [10 30 50]


## 3. Fancy Indexing in 2D Arrays

► You can select elements using **row indices** and **column indices**.
► Matching positions from each list are paired.

**Example:**
- Row indices: `[0,1,2]`  
- Column indices: `[1,2,0]`  
This selects:
- arr[0,1], arr[1,2], arr[2,0]

In [3]:
arr2 = np.array([[5,10,15], [20,25,30], [35,40,45]])
row_idx = [0, 1, 2]
col_idx = [1, 2, 0]

print("2D Array:\n", arr2)
print("\nFancy indexed result:", arr2[row_idx, col_idx])

2D Array:
[[ 5 10 15]
 [20 25 30]
 [35 40 45]]

Fancy indexed result: [10 30 35]


## 4. Boolean Masking (Detailed Explanation)

**Definition:** Boolean indexing uses a mask (True/False array) to filter elements.

► Condition generates a mask:  
`arr > 10 → [True, False, ...]`

► Only values where mask is `True` are returned.

Boolean masking is widely used in **data cleaning, filtering, feature selection**.

In [4]:
arr3 = np.array([12, 7, 19, 3, 25, 1])
mask = arr3 > 10
print("Array:", arr3)
print("Mask:", mask)
print("Filtered result:", arr3[mask])

Array: [12  7 19  3 25  1]
Mask: [ True False  True False  True False]
Filtered result: [12 19 25]


## 5. Fancy Indexing with Repeated Indices

Fancy indexing allows **repetition** of indices to duplicate elements.


In [5]:
arr4 = np.array([100, 200, 300, 400])
res = arr4[[1, 1, 3, 0, 0]]
print("Original array:", arr4)
print("Repeated indexing result:", res)

Original array: [100 200 300 400]
Repeated indexing result: [200 200 400 100 100]


## 6. Modifying Values Using Fancy Indexing

Fancy indexing can be used to change multiple elements at once.

In [6]:
arr5 = np.array([5, 10, 15, 20])
arr5[[0, 2]] = [99, 88]
print("Modified array:", arr5)

Modified array: [99 10 88 20]


## Summary
- Fancy indexing selects elements using integer lists or boolean masks.
- It allows non-contiguous and repeated selections.
- Works in both 1D and 2D arrays.
- Boolean masks enable filtering based on conditions.
- Fancy indexing returns a **copy**, unlike slicing which returns a **view**.

Mastering fancy indexing is essential for efficient data selection and preprocessing in NumPy.
