# Topic: Fancy Indexing in NumPy

**Author:** Hamna Munir  
**Repository:** Python-Libraries-for-AI-ML

---

Fancy indexing allows you to access elements of an array using **integer arrays**, **boolean masks**, and **index lists**. It is more powerful than basic slicing and is very useful in data manipulation.

## ✔️ Example 1: Integer Array Indexing

In [1]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
indices = [0, 2, 4]
result = arr[indices]
result

array([10, 30, 50])

## ✔️ Example 2: Fancy Indexing in 2D Arrays

In [2]:
arr2 = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])

# Get elements at (0,1), (1,2), (2,0)
row_idx = [0, 1, 2]
col_idx = [1, 2, 0]

fancy_result = arr2[row_idx, col_idx]
fancy_result

array([10, 30, 35])

## ✔️ Example 3: Boolean Mask Indexing

In [3]:
arr3 = np.array([12, 7, 19, 3, 25, 1])

# Pick elements > 10
mask = arr3 > 10
filtered = arr3[mask]
filtered

array([12, 19, 25])

## ✔️ Example 4: Fancy Indexing With Repeated Indices

In [4]:
arr4 = np.array([100, 200, 300, 400])

# Repeated indices
res = arr4[[1, 1, 3, 0, 0]]
res

array([200, 200, 400, 100, 100])

## ✔️ Example 5: Fancy Indexing to Modify Elements

In [5]:
arr5 = np.array([5, 10, 15, 20])

# Change values at index 0, 2
arr5[[0, 2]] = [99, 88]
arr5

array([99, 10, 88, 20])

---
### 🎉 Summary
- Fancy indexing allows selecting elements using arrays of indices.
- It works with both 1D and 2D arrays.
- Boolean masks help filter data.
- Fancy indexing can also modify elements directly.

This is a very powerful feature widely used in data analysis!