# Topic: Boolean Indexing in NumPy

**Author:** Hamna Munir  
**Repository:** Python-Libraries-for-AI-ML

---
## 📘 Introduction
Boolean Indexing allows you to filter elements from a NumPy array using **True/False conditions**. This is one of the most powerful features of NumPy because it helps extract data based on conditions without using loops.

For example:
- Extract all values greater than 10
- Filter even numbers
- Select negative values
- Replace values based on a condition

Boolean indexing works by creating a **boolean mask** (an array of True/False values) and then applying it to the original array.

---
## 🔍 How Boolean Indexing Works

When you apply a condition to a NumPy array, it returns a boolean array of **the same shape**, containing True/False.

Example:
```python
arr = np.array([1, 2, 3, 4])
mask = arr > 2
```
Mask result → `[False, False, True, True]`

Now applying mask:
```python
arr[mask]
```
→ `[3, 4]`

---
## ✔️ Let's Begin with Examples


In [1]:
import numpy as np

## ✅ Example 1: Basic Boolean Condition
Filter numbers greater than 10.

In [2]:
arr = np.array([5, 12, 7, 20, 9, 18])
result = arr[arr > 10]
print(result)

[12 20 18]


## ✅ Example 2: Filtering Even Numbers
Using modulus `% 2 == 0` to extract even values.

In [3]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
evens = arr[arr % 2 == 0]
print(evens)

[ 2  4  6  8 10]


## ✅ Example 3: Boolean Mask Array
You can also create your own True/False list.

In [4]:
arr = np.array([10, 20, 30, 40, 50])
mask = [True, False, True, False, True]
print(arr[mask])

[10 30 50]


## ✅ Example 4: Applying Multiple Conditions
Use `&` for AND, `|` for OR.

Filter values between 10 and 30.

In [5]:
arr = np.array([5, 12, 20, 35, 50])
result = arr[(arr > 10) & (arr < 30)]
print(result)

[12 20]


## ✅ Example 5: Boolean Indexing on 2D Array
Filter values greater than 10 from a matrix.

In [6]:
arr = np.array([[5, 12], [20, 7], [9, 25]])
print(arr[arr > 10])

[12 20 25]


## 🎯 Summary
- Boolean indexing helps filter data efficiently.
- Creates a mask of True/False values.
- Conditions can be combined using `&` and `|`.
- Works on both 1D and 2D arrays.

---
### ✅ End of Notebook
