# Topic: Broadcasting in NumPy

**Author:** Hamna Munir  
**Repository:** Python-Libraries-for-AI-ML  
**Goal:** Understand NumPy broadcasting rules and apply broadcasting to perform arithmetic on arrays with different shapes.

---

## Learning Outcomes
After completing this notebook, you will be able to:

- Explain what broadcasting is and when it is applied.
- Determine whether two arrays are compatible for broadcasting.
- Use broadcasting to perform element-wise arithmetic without explicit loops.
- Recognize cases where broadcasting fails and how to fix them.

---


## 1. Introduction

Broadcasting in NumPy allows arithmetic operations on arrays of different shapes by "stretching" the smaller array along the missing dimensions so the shapes become compatible. Broadcasting follows specific rules — it does not actually copy data in memory, but behaves as if the smaller array were replicated to match the larger shape.

### Broadcasting rules (summary):
1. If arrays differ in their number of dimensions, the shape of the smaller array is left-padded with ones until both shapes have the same length.
2. Arrays are compatible in a dimension if they are equal in that dimension or one of them is 1.
3. If all dimensions are compatible, broadcasting is possible and the result shape is the maximum along each dimension.

We will demonstrate these rules with examples.

In [1]:
import numpy as np
print('NumPy imported. version:', np.__version__)

NumPy imported. version: 1.24.0


## 2. Example 1 — Adding a scalar to a 1D array

A scalar is conceptually broadcast to the shape of the array and added element-wise.

In [2]:
arr = np.array([1, 2, 3])
print('Original array:', arr)
print('After adding 5:', arr + 5)

Original array: [1 2 3]
After adding 5: [6 7 8]


## 3. Example 2 — Adding a 1D row vector to a 2D array (row-wise broadcast)

A 1D array with shape (3,) can be broadcast across each row of a (2, 3) array.

In [3]:
A = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([10, 20, 30])
print('A:')
print(A)
print('b:')
print(b)
print('A + b:')
print(A + b)

A:
[[1 2 3]
 [4 5 6]]
b:
[10 20 30]
A + b:
[[11 22 33]
 [14 25 36]]


## 4. Example 3 — Adding a column vector to a 2D array (column-wise broadcast)

A column vector with shape (3,1) broadcasts against a (3,3) array to add across columns.

In [4]:
x = np.array([[1], [2], [3]])   # shape (3,1)
y = np.array([10, 20, 30])      # shape (3,)
print('x (shape (3,1)):')
print(x)
print('y (shape (3,)):')
print(y)
print('x + y (broadcasted to shape (3,3)):')
print(x + y)

x (shape (3,1)):
[[1]
 [2]
 [3]]
y (shape (3,)):
[10 20 30]
x + y (broadcasted to shape (3,3)):
[[11 21 31]
 [12 22 32]
 [13 23 33]]


## 5. Example 4 — Broadcasting with different number of dimensions

If shapes differ in length, the smaller shape is left-padded with ones. For example, shapes (3,1) and (1,4) broadcast to (3,4).

In [5]:
A = np.array([[1], [2], [3]])    # shape (3,1)
B = np.array([[10, 20, 30, 40]]) # shape (1,4)
print('A (shape (3,1)):')
print(A)
print('B (shape (1,4)):')
print(B)
print('A + B (broadcasted to shape (3,4)):')
print(A + B)

A (shape (3,1)):
[[1]
 [2]
 [3]]
B (shape (1,4)):
[[10 20 30 40]]
A + B (broadcasted to shape (3,4)):
[[11 21 31 41]
 [12 22 32 42]
 [13 23 33 43]]


## 6. Example 5 — When broadcasting fails

Broadcasting raises an error when dimensions are incompatible and none of the dimensions is 1.

In [6]:
a = np.array([1, 2, 3])
b = np.array([1, 2])
a + b

ValueError: operands could not be broadcast together with shapes (3,) (2,)

## 7. How to fix incompatible shapes

If broadcasting fails, you can often reshape or use `np.newaxis` (or `None`) to add dimensions so the shapes become compatible.

Example: reshape `b` to (2,1) or expand dims to (1,2) to make it compatible with desired operations.

In [7]:
a = np.array([1, 2, 3])        # shape (3,)
b = np.array([1, 2])           # shape (2,)
print('a:', a)
b_reshaped = b.reshape(2, 1)
print('b reshaped to (2,1):')
print(b_reshaped)
print('If we want to add row-wise, make shapes compatible; for example expand a to (3,1) or b to (1,2) depending on intent.')

a: [1 2 3]
b reshaped to (2,1):
[[1]
 [2]]
If we want to add row-wise, make shapes compatible; for example expand a to (3,1) or b to (1,2) depending on intent.


## 8. Notes and Best Practices

- Broadcasting is very powerful but can be a source of bugs if shapes are not carefully checked.
- Use `array.shape` to inspect shapes before applying operations.
- Use `np.newaxis` or `reshape` intentionally to make your intent explicit.
- Broadcasting does not copy data unnecessarily; it produces a view-like behavior for efficient computation.


## 9. Practice Tasks

1. Create an array of shape (4,3) and add a vector of shape (3,) to it — verify result.
2. Use `np.newaxis` to convert a 1D array of length 5 into a column vector and add it to a (5,5) matrix.
3. Given shapes (2,3,1) and (1,3,4), verify the broadcasted shape and perform addition.


## Summary

- Broadcasting allows element-wise operations between arrays of different shapes when they are compatible.
- Follow the broadcasting rules: align trailing dimensions, and dimensions must be equal or 1.
- When broadcasting fails, use `reshape`, `np.newaxis`, or explicit replication to make shapes compatible.

End of notebook.