# Topic: Revision and Important NumPy Functions

**Author:** Hamna Munir  
**Repository:** Python-Libraries-for-AI-ML  
**Goal:** Revise all core NumPy concepts and explore the most commonly used NumPy functions essential for AI/ML workflows.

---

## Learning Outcomes
After completing this notebook, you will be able to:

- Recall essential NumPy operations such as indexing, slicing, reshaping, broadcasting, and fancy indexing.
- Use important NumPy mathematical, statistical, and utility functions.
- Apply aggregation functions efficiently.
- Work with random number generation using `numpy.random`.
- Perform sorting, searching, and unique-value operations.

---


## 1. Importing NumPy

Import NumPy and verify the installed version.

In [1]:
import numpy as np
print('NumPy version:', np.__version__)

NumPy version: 1.24.0


## 2. Revision of Core NumPy Concepts

Before exploring important functions, here is a quick conceptual revision:

- **ND Arrays:** Multidimensional arrays used for fast computation.
- **Indexing:** Access single elements using `arr[i]` or `arr[row, col]`.
- **Slicing:** Extract subarrays using `start:end:step`.
- **Reshaping:** Change shape using `reshape()` without modifying data.
- **Fancy Indexing:** Access elements using lists of indices.
- **Boolean Indexing:** Filter elements based on conditions.
- **Broadcasting:** Perform operations on arrays of different shapes.

These concepts are used throughout NumPy-based AI/ML workflows.

## 3. Important Mathematical Functions

NumPy provides vectorized functions that operate on arrays element-wise. These functions are optimized for performance.

In [2]:
arr = np.array([1, 2, 3, 4, 5])
print('Original array:', arr)
print('Square root:', np.sqrt(arr))
print('Exponent:', np.exp(arr))
print('Sine values:', np.sin(arr))

Original array: [1 2 3 4 5]
Square root: [1.         1.41421356 1.73205081 2.         2.23606798]
Exponent: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
Sine values: [0.84147098 0.90929743 0.14112001 -0.7568025  -0.95892427]


## 4. Statistical and Aggregation Functions

These functions compute summary statistics, commonly used in data analysis and ML preprocessing.

In [3]:
arr = np.array([10, 20, 30, 40, 50])
print('Array:', arr)
print('Mean:', np.mean(arr))
print('Median:', np.median(arr))
print('Sum:', np.sum(arr))
print('Standard Deviation:', np.std(arr))
print('Minimum:', np.min(arr))
print('Maximum:', np.max(arr))

Array: [10 20 30 40 50]
Mean: 30.0
Median: 30.0
Sum: 150
Standard Deviation: 14.142135623730951
Minimum: 10
Maximum: 50


## 5. Random Number Generation

NumPy's `random` module is essential for creating synthetic datasets, weight initialization, and ML experimentation.

In [4]:
np.random.seed(42)
print('Random integers:')
print(np.random.randint(1, 10, 5))

print('\nRandom floats:')
print(np.round(np.random.rand(5),3))

print('\nRandom 2x2 matrix:')
print(np.round(np.random.rand(2,2),2))

Random integers:
[3 7 4 8 6]

Random floats:
[0.413 0.801 0.642 0.595 0.119]

Random 2x2 matrix:
[[0.48 0.32]
 [0.13 0.94]]


## 6. Sorting and Searching Functions

These functions help in organizing and locating values efficiently.

In [5]:
arr = np.array([4, 1, 7, 3, 2])
print('Original array:', arr)
print('Sorted:', np.sort(arr))
print('Indices of non-zero elements:', np.nonzero([4, 0, 7, 3, 0]))
print('Unique elements:', np.unique(arr))

Original array: [4 1 7 3 2]
Sorted: [1 2 3 4 7]
Indices of non-zero elements: [0 2 3]
Unique elements: [1 2 3 4 7]


## 7. Reshaping and Utility Functions

Some useful functions for reshaping and inspecting array structure.

In [6]:
arr = np.array([1,2,3,4,5,6])
print(arr)
print('Reshaped (2x3):')
print(arr.reshape(2,3))
print('Flattened:', arr.ravel())

[1 2 3 4 5 6]
Reshaped (2x3):
[[1 2 3]
 [4 5 6]]
Flattened: [1 2 3 4 5 6]


## 8. Practice Tasks

- Compute the variance of an array.
- Generate a 4x4 matrix of random integers.
- Extract unique values from an array and count their occurrences.
- Sort a 2D array row-wise and column-wise.
- Create a 3x3 identity matrix.


## Summary

- This notebook covered a full revision of key NumPy concepts.
- You explored essential mathematical, statistical, and random functions.
- You practiced sorting, searching, reshaping, and inspecting arrays.
- These functions are widely used in ML pipelines, preprocessing, and numerical computation.

Mastering these functions strengthens your overall NumPy foundation for AI/ML development.