# Day 01 – NumPy Practice (5 Questions)
Basic intro-level NumPy practice with outputs.

In [1]:
import numpy as np

# Q1: Create a 1D array of numbers 1 to 5
arr = np.array([1, 2, 3, 4, 5])
arr

[1 2 3 4 5]

In [2]:
import numpy as np

# Q2: Create an array of zeros with length 4
zeros_arr = np.zeros(4)
zeros_arr

array([0., 0., 0., 0.])

In [3]:
import numpy as np

# Q3: Create an array of ones with shape (2,3)
ones_arr = np.ones((2,3))
ones_arr

array([[1., 1., 1.],
       [1., 1., 1.]])

In [4]:
import numpy as np

# Q4: Generate a random integer between 1 and 10
rand_num = np.random.randint(1, 11)
rand_num

5  # (Random Example)

In [5]:
import numpy as np

# Q5: Find mean of array [10, 20, 30, 40]
arr2 = np.array([10,20,30,40])
arr2.mean()

25.0