# **Day 03 – NumPy Practice**

# List Vs Arrays
* Faster
* Convenient
* Less Memory

In [2]:
import numpy as np

In [ ]:
# Array occupy less memory as compare to list

lista = range(100)
arr1 = np.arange(100)

In [ ]:
import sys

In [ ]:
print(sys.getsizeof(87)*len(lista))

2800


In [ ]:
print(arr1.itemsize*arr1.size)

800


In [ ]:
# Array is faster than list
import time

In [ ]:
# List
x = range(10000000)
y = range(10000000,20000000)

start_time = time.time()
c = [x+y for x,y in zip(x,y)]

print(time.time()-start_time)

0.6486597061157227


In [ ]:
# Array
a = np.arange(10000000)
b = np.arange(10000000,20000000)

start_time = time.time()
c = a+b

print(time.time()-start_time)

0.08549141883850098


*   #  Indexing
*   #  Slicing
*   #  Iteration



In [3]:
arr2 = np.arange(24)
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [4]:
arr2 = np.arange(24).reshape(6,4)
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [6]:
# Indexing

arr2[3]

array([12, 13, 14, 15])

In [7]:
arr2[: , 2]

array([ 2,  6, 10, 14, 18, 22])

In [8]:
arr2[: ,1:3]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14],
       [17, 18],
       [21, 22]])

In [9]:
# Slicing

arr2[4: , 2: ]

array([[18, 19],
       [22, 23]])

In [10]:
# Iteration

for i in arr2:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
[16 17 18 19]
[20 21 22 23]


In [11]:
for i in np.nditer(arr2):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
