# **Day 07 – NumPy Practice**

# Some Important NumPy Functions

In [1]:
import numpy as np

In [4]:
np.random.random()

0.572683916150728

In [6]:
np.random.seed(1)
np.random.random()

0.417022004702574

In [8]:
# give number within given range(5,15)
np.random.uniform(5 ,15)

5.001143748173449

In [9]:
np.random.uniform(1,100,10).reshape(2,5)

array([[30.93092469, 15.52883319, 10.14152088, 19.43976093, 35.21051198],
       [40.27997995, 54.34285667, 42.50025693, 68.83673054, 21.24077272]])

In [11]:
# Generate an integer value with an given range

np.random.randint(1,10)

5

In [12]:
# Generate an array with an given range

np.random.randint(1,10,5)

array([8, 8, 2, 8, 1])

In [13]:
# Generate an 2-D array with an given range

np.random.randint(1,10,15).reshape(3,5)

array([[7, 8, 7, 2, 1],
       [2, 9, 9, 4, 9],
       [8, 4, 7, 6, 2]])

In [15]:
# find out the maximum number of an given array

a = np.random.randint(1,10,6)
a

array([4, 3, 1, 5, 3, 8])

In [16]:
np.max(a)

np.int64(8)

In [17]:
np.min(a)

np.int64(1)

In [18]:
# print the index of the maximum number
np.argmax(a)

np.int64(5)

In [19]:
# Replace the odd values of the array with "0"

a = np.random.randint(1,10,6)
a

array([8, 9, 7, 4, 8, 8])

In [20]:
a[a%2==1] = 0
a

array([8, 0, 0, 4, 8, 8])

In [21]:
# Use the "Where" functions to replace the values of the array

a = np.random.randint(1,50,6)
a

array([37, 28, 38, 20, 39,  9])

In [22]:
np.where(a%2==1 , -1 ,a)

array([-1, 28, 38, 20, -1, -1])

In [23]:
# if we print the array again print the original not the modified  array
a

array([37, 28, 38, 20, 39,  9])

In [24]:
# Use percentile Functions

a = np.random.randint(1,50,10)
a

array([33, 35, 11, 24, 16, 48, 24, 26,  8, 29])

In [25]:
a = np.sort(a)
a

array([ 8, 11, 16, 24, 24, 26, 29, 33, 35, 48])

In [26]:
np.percentile(a,50)

np.float64(25.0)

In [28]:
np.percentile(a , 99.8)

np.float64(47.76599999999999)