# **Day 05 – NumPy Practice**

# Fancy Indexing in NumPy.

In [1]:
import numpy as np

In [2]:
arr1 = np.arange(24).reshape(6,4)

In [3]:
arr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [4]:
# This is called fancy indexing
arr1[[0,2,4]]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [16, 17, 18, 19]])

# Indexing with Boolean Arrays

In [6]:
arr = np.random.randint(low = 1, high = 100 , size = 20).reshape(4,5)
arr

array([[80, 28, 37, 60, 45],
       [77, 92, 19, 15, 83],
       [69, 60, 40, 72, 66],
       [51,  1, 27, 91, 10]])

In [7]:
arr > 50

array([[ True, False, False,  True, False],
       [ True,  True, False, False,  True],
       [ True,  True, False,  True,  True],
       [ True, False, False,  True, False]])

In [8]:
# Indexing using boolean array
arr[arr>50]

array([80, 60, 77, 92, 83, 69, 60, 72, 66, 51, 91])

In [10]:
arr[(arr>50) & (arr%2 != 0)]

array([77, 83, 69, 51, 91])

In [11]:
arr[(arr>50) & (arr%2 != 0)] = 0

In [12]:
arr

array([[80, 28, 37, 60, 45],
       [ 0, 92, 19, 15,  0],
       [ 0, 60, 40, 72, 66],
       [ 0,  1, 27,  0, 10]])