# **Day 04 – NumPy Practice**

# **1-Numpy OPerations**

# Basic Operations

In [1]:
import numpy as np

In [2]:
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([4,5,6,7,8,9])

In [3]:
# Subtraction

arr1 - arr2

array([-3, -3, -3, -3, -3, -3])

In [4]:
# Multiplication
# vector Multiplication

arr1*arr2

array([ 4, 10, 18, 28, 40, 54])

In [5]:
# Scalar Multiplication
arr1*2

array([ 2,  4,  6,  8, 10, 12])

In [6]:
arr2 > 3

array([ True,  True,  True,  True,  True,  True])

In [7]:
# Dot Multiplication of matrices in numpy

arr3 = np.arange(6).reshape(2,3)
arr4 = np.arange(6,12).reshape(3,2)

In [8]:
arr3.dot(arr4)

array([[ 28,  31],
       [100, 112]])

In [9]:
arr1.dot(arr2)

np.int64(154)

In [10]:
arr4

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

# Unary Operations


*  A.max( )
*  B.min( )
*  C.sum( )


In [12]:
arr4.max()

np.int64(11)

In [13]:
arr4.min()

np.int64(6)

In [14]:
arr4.min(axis=0)

array([6, 7])

In [15]:
arr4.min(axis=1)

array([ 6,  8, 10])

In [16]:
arr4.sum()

np.int64(51)

In [17]:
arr4.sum(axis=0)

array([24, 27])

In [18]:
# Mean
arr4.mean()

np.float64(8.5)

In [20]:
# Standard deviation
arr4.std()

np.float64(1.707825127659933)

# Universal Functions
*   np.exp(A)
*   np.sin(B)
*   np.sqrt(C)




In [21]:
# Find Sin value
np.sin(arr4)

array([[-0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849],
       [-0.54402111, -0.99999021]])

In [22]:
# Find Median
np.median(arr4)

np.float64(8.5)

In [23]:
# Exponent
np.exp(arr4)

array([[  403.42879349,  1096.63315843],
       [ 2980.95798704,  8103.08392758],
       [22026.46579481, 59874.1417152 ]])

# **2-Reshaping Numpy Arrays**


*   Ravel
*   Reshape


*   Transpose
*   Stacking
*   Splitting





In [24]:
# Dimenstion of array 4

arr4.ndim

2

In [25]:
# Know change the shape of array 4 with "Ravel Function" which change the Higher dimention arrays into ID(1-dimention)
# Ravel
arr4.ravel()

array([ 6,  7,  8,  9, 10, 11])

In [30]:
# Reshape

arr4.reshape(2,3)

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [32]:
# Transpose

arr4

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [33]:
arr4.transpose()

array([[ 6,  8, 10],
       [ 7,  9, 11]])

In [34]:
# Stacking is a trick of combining two arrays of the same shape.

arr5 = np.arange(12,18).reshape(2,3)

In [35]:
arr3

array([[0, 1, 2],
       [3, 4, 5]])

In [36]:
arr5

array([[12, 13, 14],
       [15, 16, 17]])

In [37]:
# Horizontally stack

np.hstack((arr3,arr5))

array([[ 0,  1,  2, 12, 13, 14],
       [ 3,  4,  5, 15, 16, 17]])

In [38]:
# vertically stack

np.vstack((arr3,arr5))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [12, 13, 14],
       [15, 16, 17]])

In [39]:
# Splitting
# Horizontal split

np.hsplit(arr3,3)

[array([[0],
        [3]]),
 array([[1],
        [4]]),
 array([[2],
        [5]])]

In [40]:
# Vertical Split

np.vsplit(arr3 ,2)

[array([[0, 1, 2]]), array([[3, 4, 5]])]